### ISSUE TITLE
[Bug]: Interruption in particle motion (defect in movement) after build in react 

### ISSUE THREAD

**Issue by hamed-lohi** [tsparticles/tsparticles#2809]
### Contact Details

lohi.hamed@gmail.com

### What happened?

everything works fine when I use `npm run start`, but after build (`npm run build`) there is Interruption in particle motion.

my react version is 17.0.2 and use typescript.

### Version

1.38.0

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
const options: ISourceOptions = 
  {
    retina_detect: false,
    detectRetina: false,
    "background": {
      "color": {
        "value": "#00000095"
      },
      "position": "50% 50%",
      "repeat": "no-repeat",
      "size": "cover",
      "opacity": 1,
      "image": "url('/img/bg1.jpg')"
    },

    "backgroundMask": {
      "composite": "destination-out",
      "cover": {
        "color": {
          "value": {
            "r": 255,
            "g": 255,
            "b": 255
          }
        },
        "opacity": 1
      },
      "enable": true
    },

    "fullScreen": {
      "enable": false,
      "zIndex": -10
    },
    "interactivity": {
      "events": {
        "onClick": {
          "enable": true,
          "mode": "push"
        },
        "onDiv": {
          "selectors": "#repulse-div",
          "mode": "repulse"
        },
        "onHover": {
          "enable": true,
          "mode": "bubble",
          "parallax": {
            "force": 60
          }
        }
      },
      "modes": {
        "bubble": {
          "distance": 400,
          "duration": 2,
          "opacity": 0.8,
          "size": 40
        },
        "grab": {
          "distance": 400
        },
        "slow": {
          "factor": 1,
          "radius": 0
        }
      }
    },
    "particles": {
      "color": {
        "value": "#ffffff"
      },
      "links": {
        "color": {
          "value": "#ffffff"
        },
        "distance": 150,
        "enable": true,
        "opacity": 0.4,
        "shadow": {
          "color": {
            "value": "lime"
          }
        }
      },
      "move": {
        "attract": {
          "rotate": {
            "x": 600,
            "y": 1200
          }
        },
        "enable": true,
        "outModes": {
          "bottom": "out",
          "left": "out",
          "right": "out",
          "top": "out",
          "default": "none"
        },
        "direction": "right",
        "speed": 2
      },
      "number": {
        "density": {
          "enable": true,
        },
        "value": 60
      },
      "opacity": {
        "value": {
          "min": 0.1,
          "max": 0.5
        },
        "animation": {
          "enable": true,
          "speed": 1,
          "minimumValue": 0.1
        }
      },
      "shape": {
        "options": {
          "polygon": {
            "sides": 5
          },
          "star": {
            "sides": 5
          },
        },
        "type": "square"
      },

      "size": {
        "random": {
          "enable": true,
          "minimumValue": 0,
        },
        "value": {
          "min": 5,
          "max": 20
        },
        "animation": {
          "speed": 10,
          "minimumValue": 0.1
        }
      },
    }
  };


<Particles
          id="tsparticles"
          init={particlesInit}
          loaded={particlesLoaded}
          options={options} />
```

### What browsers are you seeing the problem on?

In most browsers

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Do you have some errors in the console? Did you start from a create-react-app project or a different configuration?

**Comment by hamed-lohi** [comment]
There is no error in console, yes I start from a `npm create-react-app my-app --template typescript`

**Comment by matteobruni** [comment]
I tested a new app configured with TypeScript, I built the project and served using `serve` and with your config the particles are not stopping.

I used `1.38.0` and not the upcoming `1.39.0` to see if the current version is working.

**Comment by hamed-lohi** [comment]
This problem occurs when I create a production build by execute this command `npm run build` and transfer my app in the `build/` folder to host .
note: that the particles are not stopping, But they have delays or interruptions in movement
I also tried the previous version, it still had problems

**Comment by matteobruni** [comment]
I have a published react website here: https://tsparticles.github.io/react-auth-template/#/login

Do you see the issue here?

**Comment by hamed-lohi** [comment]
How did you publish?
Please do with my options I mentioned earlier

**Comment by matteobruni** [comment]
> How did you publish?
> Please do with my options I mentioned earlier

It’s a simple GitHub pages publish, publish files are in the gh-pages branch. Can you try with different options to see if the problem persists? I can’t reproduce it on my side. Try sharing a full sample.

**Comment by hamed-lohi** [comment]
I published here: [https://t.basimdata.ir/](https://t.basimdata.ir/)

**Comment by matteobruni** [comment]
I don't see the issue in your website, sorry. I don't see any interruptions or delays.

**Comment by hamed-lohi** [comment]
https://user-images.githubusercontent.com/16226722/148494000-a5267adf-9453-4254-ae32-14e84f49a7b4.mp4

**Comment by hamed-lohi** [comment]
I found the reason for this issue, there is a problem with the bundle file that occurs when using the `npm run build` command.
now I am building the project with `Webpack` and there is no interruption
[https://n.basimdata.ir/](https://n.basimdata.ir/)

**Comment by hamed-lohi** [comment]
This is a really useful and complete tool. Congratulations to you.
thank you

**Comment by mutheusalmeida** [comment]
> This is a really useful and complete tool. Congratulations to you. thank you

Could you share your solution?

**Comment by hamed-lohi** [comment]
If use webpack for build, this problem almost solved .
[following in stackoverflow](https://stackoverflow.com/q/70625054/8730051)
Do you want webpack configs ?

**Comment by mutheusalmeida** [comment]
> If use webpack for build, this problem almost solved . [following in stackoverflow](https://stackoverflow.com/q/70625054/8730051) Do you want webpack configs ?

Thanks for your reply. I solved by changing the browserlist in package.json. It seems to be an issue with webgl API + the build tool, I don't know

**Comment by brenoprata10** [comment]
Being more direct, i changed my browserslist to this and i already noticed a huge difference
```
"browserslist": {
                "production": [
                        "> 5%",
                        "not dead",
                        "not op_mini all"
                ],
                "development": [
                        "> 5%",
                        "not dead",
                        "not op_mini all"
                ]
        },
```

**Comment by hamed-lohi** [comment]
But still the problem is not completely solved

**Comment by matteobruni** [comment]
I should say good timing, I think I've replicated the issue now while testing some new features.
It looks related to the `refresh` method of the `Container` object.
There's a huge performance drop on every reload button of the demos page on the website, and also in the vanilla demo inside the project.
Changing from `refresh` to `tsParticles.load` "solves" the issue, just because it destroys the `Container` object instead of refreshing it.
This is now the maximum priority on my list.

**Comment by matteobruni** [comment]
`1.39.3` should fix this issue, the update is going to be available very soon

**Comment by brenoprata10** [comment]
Good job guys, keep up with the great work 👌

**Comment by hamed-lohi** [comment]
> 1.39.3 should fix this issue, the update is going to be available very soon

Thanks for your update, but the performance is still low and there is a slight interruption in particle motion in react-tsparticles .
maybe this screenshot from browser inspect performance tab is useful:
(Warning Long task took 59.73 ms.)
![inspect](https://user-images.githubusercontent.com/16226722/152200563-fe408aa9-be65-4f86-9085-cefdbdf13943.png)

**Comment by matteobruni** [comment]
It doesn’t help since it doesn’t contain anything that I can reproduce. The draw took 3 frames and it’s really strange.

Can you paste the configuration?

**Comment by mutheusalmeida** [comment]
> I should say good timing, I think I've replicated the issue now while testing some new features. It looks related to the `refresh` method of the `Container` object. There's a huge performance drop on every reload button of the demos page on the website, and also in the vanilla demo inside the project. Changing from `refresh` to `tsParticles.load` "solves" the issue, just because it destroys the `Container` object instead of refreshing it. This is now the maximum priority on my list.

I have faced the same issue with another library that's built upon three.js and changing the browserlist solved both.

But this problem still persists on high resolution devices only

**Comment by hamed-lohi** [comment]
> It doesn’t help since it doesn’t contain anything that I can reproduce. The draw took 3 frames and it’s really strange.
> Can you paste the configuration?

```
  const options: any =
  {
    "detectRetina": true,
    "background": {
      "image": "linear-gradient(to right, yellow,orange,red,green,blue,indigo,violet)"
    },
    "backgroundMask": {
      "composite": "destination-out",
      "cover": {
        "color": {
          "value": {
            "r": 255,
            "g": 255,
            "b": 255
          }
        },
        "opacity": 0.98
      },
      "enable": true
    },
    "fullScreen": {
      "enable": false,
      "zIndex": -10
    },
    "pauseOnOutsideViewport": true,
    "motion": {
      "disable": true
    },
    "fpsLimit": 60,
    "interactivity": {
      "events": {
        "onClick": {
          "enable": false,
          "mode": "push"
        },
        "onDiv": {
          "selectors": "#repulse-div",
          "mode": "repulse"
        },
        "onHover": {
          "enable": true,
          "mode": "repulse",
          "parallax": {
            "force": 30
          }
        }
      },
      "modes": {
        "repulse": {
          "distance": 50,
          "duration": 0.5,
          "easing": 'easeOutBack',
          "factor": 20,
          "maxSpeed": 10,
          "speed": 2,
        }
      }
    },
    "particles": {
      "bounce": { "distance": 50 },
      "color": {
        "value": "#ffffff",
      },
      "links": {
        "blink": true,
        "color": {
          "value": "#ffffff",
        },
        "frequency": 1,
        "distance": 80,
        "enable": true,
        "opacity": 0.4,
      },
      "move": {
        "attract": {
          "enable": false,
          "rotate": {
            "x": 400,
            "y": 700
          }
        },
        "enable": true,
        "direction": "right",
        "speed": 2,
      },
      "number": {
        "density": {
          "enable": true,
          "area": 800,
        },
        "limit": 250,
        "value": 250,
      },
      "shape": {
        "options": {
          "polygon": {
            "sides": 5
          },
          "star": {
            "sides": 5
          },
        },
        "type": 'line'
      },
      "size": {
        "random": {
          "enable": false,
          "minimumValue": 0,
        },
        "value": 8,
      },
    }
  };

  return (
    <header id='header'>
      <div className='intro'>

        <Particles
          id="tsparticles"
          options={options}
        />

   ...
```

**Comment by hamed-lohi** [comment]
> I have faced the same issue with another library that's built upon three.js and changing the browserlist solved both.
> But this problem still persists on high resolution devices only

`mutheus` is right, my monitor is 24 inches and my screen resolution is: 1920x1080
